export const FAIL_CLIENT = 'FAIL_SERVICE';
export const SUCCESS_CLIENT = 'SUCCESS_SERVICE';
export const MIGRATION_CLIENT = 'MIGRATION_SERVICE';
export const MIGRATION_FAILED = 'MIGRATION_FAILED';
export const MIGRATION_VALIDATED = 'MIGRATION_VALIDATED';
export const MIGRATION_READY = 'MIGRATION_READY';